#!/bin/bash
# =============================================================
# docker-setup.sh — Docker Project Scaffolding Tool
# IT135 Introduction to Linux — Final Project Script
# Author: [Your Name] — North Seattle College WN26
#
# PURPOSE:
#   Automates the repetitive task of setting up a new Docker
#   project from scratch. Creates a folder structure, generates
#   a Dockerfile, and makes all scripts executable — tasks a
#   Full-Stack Developer or DevOps Engineer does manually every
#   time they start a new project.
#
# LINUX TOOLS USED:
#   grep    — reads back the Dockerfile to confirm base image
#   awk     — extracts the image name from the FROM line
#   find    — locates .sh files to make executable
#   for     — loops through folders to create them, scripts to chmod
#   if/then — validates input and checks for existing directories
#   read    — gets project name and type from the user
#   case    — handles project type menu selection
#   chmod   — makes discovered shell scripts executable
# =============================================================

# --- COLORS ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

# --- HEADER ---
clear
echo -e "${CYAN}${BOLD}"
echo "  ╔══════════════════════════════════════════╗"
echo "  ║     Docker Project Setup Tool v1.0      ║"
echo "  ║     IT135 — North Seattle College       ║"
echo "  ╚══════════════════════════════════════════╝"
echo -e "${RESET}"

# --- STEP 1: Get project name from user ---
echo -e "${BOLD}Step 1 of 4 — Project Name${RESET}"
read -p "  Enter your project name (no spaces): " PROJECT_NAME

# if/then — validate that the user actually typed something
if [ -z "$PROJECT_NAME" ]; then
    echo -e "${RED}  Error: Project name cannot be empty. Exiting.${RESET}"
    exit 1
fi

# if/then — check if the project folder already exists
if [ -d "/app/$PROJECT_NAME" ]; then
    echo -e "${YELLOW}  Warning: A folder named '$PROJECT_NAME' already exists.${RESET}"
    read -p "  Overwrite it? [y/n]: " confirm
    if [ "$confirm" != "y" ]; then
        echo -e "${RED}  Cancelled.${RESET}"
        exit 0
    fi
fi

echo ""

# --- STEP 2: Choose project type ---
echo -e "${BOLD}Step 2 of 4 — Project Type${RESET}"
echo "  What kind of project are you building?"
echo ""
echo "  1)  Web App       (nginx base image)"
echo "  2)  Python App    (python:3.11 base image)"
echo "  3)  Linux Sandbox (ubuntu:22.04 base image)"
echo "  4)  Node.js App   (node:18 base image)"
echo ""
read -p "  Select project type [1-4]: " TYPE_CHOICE

# case statement — set the base image based on user choice
case $TYPE_CHOICE in
    1) BASE_IMAGE="nginx:latest";    PROJECT_TYPE="Web App" ;;
    2) BASE_IMAGE="python:3.11";     PROJECT_TYPE="Python App" ;;
    3) BASE_IMAGE="ubuntu:22.04";    PROJECT_TYPE="Linux Sandbox" ;;
    4) BASE_IMAGE="node:18";         PROJECT_TYPE="Node.js App" ;;
    *)
        echo -e "${RED}  Invalid choice. Defaulting to Ubuntu sandbox.${RESET}"
        BASE_IMAGE="ubuntu:22.04"
        PROJECT_TYPE="Linux Sandbox"
        ;;
esac

echo ""

# --- STEP 3: Create folder structure ---
echo -e "${BOLD}Step 3 of 4 — Creating Project Structure${RESET}"

# Define the folders every project needs
FOLDERS=("src" "logs" "config" "scripts")

# for loop — create each folder in the list
for FOLDER in "${FOLDERS[@]}"; do
    mkdir -p "/app/$PROJECT_NAME/$FOLDER"
    echo -e "  ${GREEN}[+]${RESET} Created /app/$PROJECT_NAME/$FOLDER"
done

# Generate the Dockerfile inside the new project folder
cat > "/app/$PROJECT_NAME/Dockerfile" << EOF
# Auto-generated by docker-setup.sh
# Project: $PROJECT_NAME
# Type: $PROJECT_TYPE
FROM $BASE_IMAGE

WORKDIR /app

COPY . .

RUN echo "Project $PROJECT_NAME is ready."
EOF

echo -e "  ${GREEN}[+]${RESET} Generated Dockerfile"

# Create a starter README
echo "# $PROJECT_NAME" > "/app/$PROJECT_NAME/README.md"
echo "Project type: $PROJECT_TYPE" >> "/app/$PROJECT_NAME/README.md"
echo "Created with docker-setup.sh — IT135 NSC" >> "/app/$PROJECT_NAME/README.md"
echo -e "  ${GREEN}[+]${RESET} Generated README.md"

echo ""

# --- STEP 4: Find and chmod any shell scripts ---
echo -e "${BOLD}Step 4 of 4 — Making Scripts Executable${RESET}"

# find — locate all .sh files in the new project directory
# for loop — run chmod +x on each one found
FOUND_SCRIPTS=$(find "/app/$PROJECT_NAME" -name "*.sh")

if [ -z "$FOUND_SCRIPTS" ]; then
    echo -e "  ${YELLOW}[~]${RESET} No .sh scripts found to chmod."
else
    for SCRIPT in $FOUND_SCRIPTS; do
        chmod +x "$SCRIPT"
        echo -e "  ${GREEN}[+]${RESET} chmod +x applied to $SCRIPT"
    done
fi

echo ""

# --- SUMMARY REPORT ---
echo -e "${CYAN}${BOLD}"
echo "  ╔══════════════════════════════════════════╗"
echo "  ║           Setup Complete!               ║"
echo "  ╚══════════════════════════════════════════╝"
echo -e "${RESET}"

# grep + awk — read back the generated Dockerfile and extract the base image
# This confirms the file was written correctly
CONFIRMED_IMAGE=$(grep "^FROM" "/app/$PROJECT_NAME/Dockerfile" | awk '{print $2}')

echo -e "  ${BOLD}Project:${RESET}     $PROJECT_NAME"
echo -e "  ${BOLD}Type:${RESET}        $PROJECT_TYPE"
echo -e "  ${BOLD}Base image:${RESET}  $CONFIRMED_IMAGE"
echo -e "  ${BOLD}Location:${RESET}    /app/$PROJECT_NAME/"
echo ""
echo -e "  ${YELLOW}To build your container:${RESET}"
echo -e "  cd /app/$PROJECT_NAME && docker build -t $PROJECT_NAME ."
echo ""
echo -e "  ${GREEN}Ready to build!${RESET}"
echo ""

read -p "  Press Enter to return to the main menu..." pause
